# Generated by Django 3.1.2 on 2020-10-20 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grouptasks', '0004_auto_20200910_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
